version: '2.1'
services:
  postgres:
    extends:
      file: ../postgres/docker-compose.yml
      service: postgres
    ports: ['5432:5432']
    networks:
      private.network.org:
        aliases:
        - postgres.private.network.org
  base-streaming-file-server:
    build: ./base-streaming-file-server
    networks: [private.network.org]
  file-items-service:
    build:
      context: ../../..
      dockerfile: ./modules/docker/all/file-items-service/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      base-streaming-file-server:
        condition: service_started
    environment:
      DB_HOST: postgres.private.network.org
    ports: ['8001:8001']
    networks:
      private.network.org:
        aliases:
        - file-items-service.private.network.org
  file-server:
    build:
      context: ../../..
      dockerfile: ./modules/docker/all/file-server/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      base-streaming-file-server:
        condition: service_started
      file-items-service:
        condition: service_healthy
    environment:
      APP_UPLOAD_PATH: /tmp
      FILE_ITEMS_REST_SERVICE_HOST: file-items-service.private.network.org
      FILE_ITEMS_REST_SERVICE_PORT: 8001
    ports: ['8002:8002']
    volumes:
    - ./build:/var/file-storage:rw
    networks:
      private.network.org:
        aliases:
        - file-server.private.network.org
  nginx:
    build: ./nginx
    depends_on:
      postgres:
        condition: service_healthy
      base-streaming-file-server:
        condition: service_started
      file-items-service:
        condition: service_healthy
      file-server:
        condition: service_healthy
    ports: ['80:80']
    networks:
      private.network.org:
        aliases:
        - nginx
        - proxy
        - reverse-proxy
        - nginx.private.network.org
        - proxy.private.network.org
        - reverse-proxy.private.network.org
      public.network.org:
        aliases: []
networks:
  private.network.org:
    driver: bridge
  public.network.org:
    driver: bridge
