version: '2.1'
services:
  postgres:
    extends:
      file: ../postgres/docker-compose.yml
      service: postgres
    networks:
      private.network.org:
        aliases:
          - postgres.private.network.org
  base-streaming-file-server:
    build: ./base-streaming-file-server
    networks: [private.network.org]
  file-items-service:
    build:
      context: ../../..
      dockerfile: ./modules/docker/all/file-items-service/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      base-streaming-file-server:
        condition: service_started
    environment:
      DB_HOST: postgres.private.network.org
    networks:
      private.network.org:
        aliases:
          - file-items-service.private.network.org
  file-server:
    build:
      context: ../../..
      dockerfile: ./modules/docker/all/file-server/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      base-streaming-file-server:
        condition: service_started
      file-items-service:
        condition: service_healthy
    environment:
      APP_UPLOAD_PATH: /tmp
      FILE_ITEMS_REST_SERVICE_HOST: file-items-service.private.network.org
      FILE_ITEMS_REST_SERVICE_PORT: 8001
    volumes:
      - ./build:/var/file-storage:rw
    networks:
      private.network.org:
        aliases:
          - file-server.private.network.org
  haproxy:
    build: ./haproxy
    depends_on:
      postgres:
        condition: service_healthy
      base-streaming-file-server:
        condition: service_started
      file-items-service:
        condition: service_healthy
      file-server:
        condition: service_healthy
    ports: ['80:80']
    networks:
      private.network.org:
        aliases:
          - proxy
          - haproxy
          - reverse-proxy
          - proxy.private.network.org
          - haproxy.private.network.org
          - reverse-proxy.private.network.org
      public.network.org:
        aliases: []
networks:
  private.network.org:
    driver: bridge
  public.network.org:
    driver: bridge
